
export const Model = [
  ["R2","APP","1.1","Office-Produkte","Anwendung"],
  ["R2","APP","1.2","Web-Browser","Anwendung"],
  ["R2","APP","1.4","Mobile Anwendungen (Apps)","Anwendung"],
  ["R2","APP","2.1","Allgemeiner Verzeichnisdienst","Anwendung"],
  ["R2","APP","2.2","Active Directory","Anwendung"],
  ["R2","APP","2.3","OpenLDAP","Anwendung"],
  ["R2","APP","3.1","Webanwendungen","Anwendung"],
  ["R2","APP","3.2","Webserver","Anwendung"],
  ["R2","APP","3.3","Fileserver","Anwendung"],
  ["R2","APP","3.4","Samba","Anwendung"],
  ["R2","APP","3.6","DNS-Server","Anwendung"],
  ["R2","APP","4.2","SAP-ERP-System","Anwendung"],
  ["R2","APP","4.3","Relationale Datenbanksysteme","Anwendung"],
  ["R2","APP","4.6","SAP ABAP-Programmierung","Anwendung"],
  ["R2","APP","5.1","Allgemeine Groupware","Anwendung"],
  ["R2","APP","5.2","Microsoft Exchange und Outlook","Anwendung"],
  ["R2","CON","2","Datenschutz","Informationsverbund/übergeordnete Aspekte"],
  ["R2","CON","4","Auswahl und Einsatz von Standardsoftware","Informationsverbund/übergeordnete Aspekte"],
  ["R2","DER","1","Detektion von sicherheitsrelevanten Ereignissen","Informationsverbund/übergeordnete Aspekte"],
  ["R2","DER","2.1","Behandlung von Sicherheitsvorfällen","Informationsverbund/übergeordnete Aspekte"],
  ["R2","IND","1","Betriebs- und Steuerungstechnik","Informationsverbund/übergeordnete Aspekte"],
  ["R2","IND","2.1","Allgemeine ICS-Komponente","IT-System"],
  ["R2","IND","2.2","Speicherprogrammierbare Steuerung (SPS)","IT-System"],
  ["R2","IND","2.3","Sensoren und Aktoren","IT-System"],
  ["R2","IND","2.4","Maschine","IT-System"],
  ["R2","IND","2.7","Safety Instrumented Systems","IT-System"],
  ["R2","INF","1","Allgemeines Gebäude","Gebäude/Raum"],
  ["R2","INF","10","Besprechungs-, Veranstaltungs- und Schulungsräume","Gebäude/Raum"],
  ["R2","INF","2","Rechenzentrum sowie Serverraum","Gebäude/Raum"],
  ["R2","INF","3","Elektrotechnische Verkabelung","Gebäude/Raum"],
  ["R2","INF","4","IT-Verkabelung","Gebäude/Raum"],
  ["R2","INF","5","Raum sowie Schrank für technische Infrastruktur","Gebäude/Raum"],
  ["R2","INF","6","Datenträgerarchiv","Gebäude/Raum"],
  ["R2","INF","7","Büroarbeitsplatz","Gebäude/Raum"],
  ["R2","INF","8","Häuslicher Arbeitsplatz","Gebäude/Raum"],
  ["R2","INF","9","Mobiler Arbeitsplatz","Informationsverbund/übergeordnete Aspekte"],
  ["R2","NET","1.1","Netzarchitektur und -design","Netz"],
  ["R2","NET","1.2","Netzmanagement","IT-System"],
  ["R2","NET","2.1","WLAN-Betrieb","Netz"],
  ["R2","NET","2.2","WLAN-Nutzung","IT-System"],
  ["R2","NET","3.1","Router und Switches","IT-System"],
  ["R2","NET","3.2","Firewall","IT-System"],
  ["R2","NET","3.3","VPN","IT-System"],
  ["R2","NET","4.1","TK-Anlagen","IT-System"],
  ["R2","NET","4.2","VoIP","IT-System"],
  ["R2","NET","4.3","Faxgeräte und Faxserver","IT-System"],
  ["R2","OPS","2.1","Outsourcing für Kunden","Informationsverbund/übergeordnete Aspekte"],
  ["R2","OPS","2.2","Cloud-Nutzung","Informationsverbund/übergeordnete Aspekte"],
  ["R2","SYS","1.1","Allgemeiner Server","IT-System"],
  ["R2","SYS","1.2.2","Windows Server 2012","IT-System"],
  ["R2","SYS","1.3","Server unter Linux und Unix","IT-System"],
  ["R2","SYS","1.5","Virtualisierung","IT-System"],
  ["R2","SYS","1.7","IBM Z-System","IT-System"],
  ["R2","SYS","1.8","Speicherlösungen","IT-System"],
  ["R2","SYS","2.1","Allgemeiner Client","IT-System"],
  ["R2","SYS","2.2.2","Clients unter Windows 8.1","IT-System"],
  ["R2","SYS","2.2.3","Clients unter Windows 10","IT-System"],
  ["R2","SYS","2.3","Clients unter Unix","IT-System"],
  ["R2","SYS","2.4","Clients unter macOS","IT-System"],
  ["R2","SYS","3.1","Laptops","IT-System"],
  ["R2","SYS","3.2.1","Allgemeine Smartphones und Tablets","IT-System"],
  ["R2","SYS","3.2.2","Mobile Device Management (MDM)","Informationsverbund/übergeordnete Aspekte"],
  ["R2","SYS","3.2.3","iOS (for Enterprise)","IT-System"],
  ["R2","SYS","3.2.4","Android","IT-System"],
  ["R2","SYS","3.3","Mobiltelefon","IT-System"],
  ["R2","SYS","4.1","Drucker, Kopierer und Multifunktionsgeräte","IT-System"],
  ["R2","SYS","4.3","Eingebettete Systeme","IT-System"],
  ["R2","SYS","4.4","Allgemeines IoT-Gerät","IT-System"],
  ["R2","SYS","4.5","Wechseldatenträger","IT-System"],
  ["R3","CON","1","Kryptokonzept","Informationsverbund/übergeordnete Aspekte"],
  ["R3","CON","5","Entwicklung und Einsatz von Individualsoftware","Anwendung"],
  ["R3","CON","7","Informationssicherheit auf Auslandsreisen","Informationsverbund/übergeordnete Aspekte"],
  ["R3","CON","8","Software-Entwicklung","Informationsverbund/übergeordnete Aspekte"],
  ["R3","CON","9","Informationsaustausch","Informationsverbund/übergeordnete Aspekte"],
  ["R3","DER","2.2","Vorsorge für die IT-Forensik","Informationsverbund/übergeordnete Aspekte"],
  ["R3","DER","2.3","Bereinigung weitreichender Sicherheitsvorfälle","Informationsverbund/übergeordnete Aspekte"],
  ["R3","DER","3.1","Audits und Revisionen","Informationsverbund/übergeordnete Aspekte"],
  ["R3","DER","3.2","Revisionen auf Basis des Leitfadens IS-Revision","Informationsverbund/übergeordnete Aspekte"],
  ["R3","DER","4","Notfallmanagement","Informationsverbund/übergeordnete Aspekte"],
  ["R3","OPS","1.2.2","Archivierung","Informationsverbund/übergeordnete Aspekte"],
  ["R3","OPS","1.2.4","Telearbeit","Informationsverbund/übergeordnete Aspekte"],
  ["R3","OPS","1.2.5","Fernwartung","Informationsverbund/übergeordnete Aspekte"],
  ["R3","OPS","3.1","Outsourcing für Dienstleister","Informationsverbund/übergeordnete Aspekte"],
  ["R3","ORP","5","Compliance Management (Anforderungsmanagement)","Informationsverbund/übergeordnete Aspekte"],
];
